# Reference: https://docs.sonarqube.org/display/PLUG/Code+Coverage+by+Unit+Tests+for+Java+Project
sonar.projectKey=com.java:SonarQubeCoverageJava
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.junit.reportPaths=target/surefire-reports
sonar.jacoco.reportPaths=target/jacoco.exec
mvn clean verify sonar:sonar \
  -Dsonar.projectKey=ganesh \
  -Dsonar.projectName='ganesh' \
  -Dsonar.host.url=http://localhost:9005 \
  -Dsonar.token=sqp_82c42b59b2c22708f83e9c453dfc4448e579df02
